baseurl = "/"
title = "Home"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Nicholas Clark"
disqusShortname = "NC"
googleAnalytics = "XXX"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "My Name"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Nicholas J Clark"
    description = "Statistics and Data Science Projects"
    linkedin = "https://www.linkedin.com/in/nicholas-clark-4a822513a/"
    email = "nicholas.clark@westpoint.edu"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = true
    readingTimeText = "Estimated reading time:"
    author = "Nicholas Clark"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
    
[[menu.main]]
    name = "Current Projects"
    url = "/project/"
    weight = 4

[[menu.main]]
    name = "CV"
    url = "/files/cv.pdf"
    weight = 100
    
[[menu.main]]
    name = "MA376 Course Notes"
    url = "/courses/"
    weight = 100