---
title: Prior to Lesson 1
author: Nicholas J. Clark
date: '2020-01-03'
slug: prior-to-lesson-1
categories: ["R"]
tags: ["RMarkdown"]
description: ''
---

Welcome to MA376!  Prior to class please ensure you have a \textbf{working} version of R [Available Here](https://www.r-project.org/) and R Studio, [Available Here](https://rstudio.com/products/rstudio/).  THe majority of this course will be conducted in R, but if you want to use Python, there's nothing stopping you!

In R Studio run `library(tidyverse)`  If you get an error, you need to install the package via `install.packages("tidyverse")`.  If you need a referesher on `tidyverse`, I'd highly recommend [R4DS](https://r4ds.had.co.nz/).


The textbook for this course is [Intermediate Statistical Investigations](http://www.isi-stats.com/) which can be purchased through the bookstore.  We will also be doing explorations from the textbook which involve the data sets located at [http://www.isi-stats.com/isi2/applets.html](http://www.isi-stats.com/isi2/applets.html).

Please read the course website and the course calendar at [https://www.nicholasjsclark.com/courses/testpost/](https://www.nicholasjsclark.com/courses/testpost/) or through clicking the link at the top of this page.

In this course we will be working through a variety of statistical explorations.  My expectation is that you complete the assignment using Rmarkdown preferably knit to pdf.  If you have issues knitting to pdf the first thing to do is ensure you have MikTex installed.  One resource for setting this up is at [This Website](https://medium.com/@sorenlind/create-pdf-reports-using-r-r-markdown-latex-and-knitr-on-windows-10-952b0c48bfa9).  If you continue to have problems knitting to pdf you may have to follow the follwing steps (credit to Timesaver from [this issue](https://community.rstudio.com/t/rmarkdown-knit-pdf-issues/10102/7):

\begin{itemize}
\item Start MikTex console
\item Click on ``Restart as Adminstrator"
\item Then choose ``Always install missing packages on the fly"
\item Close the console
\item Restart RStudio
\end{itemize}

