---
title: Daily Cases
author: Clark
date: '2020-03-15'
slug: daily-cases
categories: []
tags: []
description: ''
---


Place Holder

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
```


```{r}
current.data<-read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv")


us.dat<-current.data %>% filter(`Country/Region`=="US")

us.sum<-us.dat %>% select(-`Country/Region`,-Lat,-Long)
states.only<-us.sum[1:52,]

#names(states.only)

Total.Cases<-rowSums(states.only[,-1])

daily.update<-cbind(states.only[,1],states.only[,(ncol(states.only)-1)],states.only[,ncol(states.only)])

daily.update.mod<-daily.update %>% mutate(State = `Province/State`,`Num Cases`=daily.update[,3],`Last 24`=daily.update[,3]-daily.update[,2])%>%
  select(State,`Num Cases`,`Last 24`)

a<-daily.update.mod
t1 = a[1:(nrow(a)/3),]
t2 = a[(nrow(a)/3+1):(2*nrow(a)/3),]
t3 = a[(2*nrow(a)/3+1):nrow(a),]
x_html<-knitr::kable(list(t1,t2,t3),"html",row.names = FALSE)
x_html
```
